pipeline {
    agent any

    environment {
        JAVA_HOME = '/usr/lib/jvm/java-11-openjdk-amd64'
        PATH = "${JAVA_HOME}/bin:${env.PATH}"
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Repository already checked out in Declarative: Checkout SCM.'
            }
        }

        stage('Compile') {
            steps {
                sh 'ls -R' // Debug: List workspace contents
                sh 'javac HelloWorld.java' // Update path if necessary
            }
        }

        stage('Run') {
            steps {
                sh 'java HelloWorld'
            }
        }

        stage('Test') {
            steps {
                echo 'Add your test steps here if needed.'
            }
        }

        stage('Clean Up') {
            steps {
                sh 'rm -f HelloWorld.class'
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution complete.'
        }
    }
}
