pipeline {
    agent any

    environment {
        JAVA_HOME = '/usr/lib/jvm/java-11-openjdk-amd64'
        PATH = "${JAVA_HOME}/bin:${env.PATH}"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Gaurigithub-p/Jenkins-Zero-To-Hero.git'
            }
        }

        stage('Compile') {
            steps {
                script {
                    sh 'javac HelloWorld.java'
                }
            }
        }

        stage('Run') {
            steps {
                script {
                    sh 'java HelloWorld'
                }
            }
        }

        stage('Test') {
            steps {
                echo 'Add your test steps here if needed.'
            }
        }

        stage('Clean Up') {
            steps {
                sh 'rm -f HelloWorld.class'
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution complete.'
        }
    }
}

